#!/usr/bin/env python3
"""Turn src/system.fth into a ca65 byte table the kernel can interpret at boot.

The cold-start code points the outer interpreter at this text and lets it
compile itself before the keyboard is ever read.  Keeping the source as real
Forth rather than hand-escaped .byte directives makes it editable; this script
handles the quoting, and strips comments and blank lines because both cost
image space and boot time (every token is a linear dictionary search).

    python3 tools/mkboot.py src/system.fth build/bootsrc.inc
"""

import pathlib
import sys

MAX_LINE = 200          # the terminal input buffer is one page at $0200


def emit(line: str) -> str:
    """One source line as .byte directives, with $22 standing in for a quote."""
    pieces = []
    for index, chunk in enumerate(line.split('"')):
        if index:
            pieces.append("$22")
        if chunk:
            pieces.append('"' + chunk + '"')
    pieces.append("$0D")
    return "        .byte   " + ", ".join(pieces)


def main(argv):
    if len(argv) != 3:
        print(__doc__)
        return 2
    src, dst = pathlib.Path(argv[1]), pathlib.Path(argv[2])

    out = [
        f"; Generated by tools/mkboot.py from {src}.  Do not edit.",
        "BOOTSRC:",
    ]
    kept = 0
    for number, raw in enumerate(src.read_text().splitlines(), 1):
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("\\"):
            continue                                    # comment or blank
        if len(line) > MAX_LINE:
            raise SystemExit(f"{src}:{number}: line is {len(line)} chars, "
                             f"over the {MAX_LINE}-char input buffer")
        out.append(emit(line))
        kept += 1
    out.append("        .byte   $00")

    dst.write_text("\n".join(out) + "\n")
    print(f"wrote {dst}: {kept} lines of Forth")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
