#!/usr/bin/env python3
"""Pack src/system.fth into disk sectors for the kernel to read at boot.

The cold-start code points the outer interpreter at this text and lets it
compile itself before the keyboard is ever read.  Keeping the source as real
Forth rather than hand-escaped .byte directives makes it editable; this script
handles the packing, and strips comments and blank lines because both cost
boot time -- every token is a dictionary search.

It used to emit a ca65 byte table, which meant the whole of system.fth --
nearly ten kilobytes of text -- sat in the image for the life of the session,
having been read exactly once.  The kernel and the dictionary share one 32K
region, so that text was costing ten times what was left for the user.  Now
it goes on the disk and the kernel streams it a sector at a time.

No line crosses a sector boundary, so the reader never has to hold a partial
one: a zero byte means "this sector is finished", and the next one is read
on demand.

    python3 tools/mkboot.py src/system.fth build/bootsrc.bin build/srcsecs.inc
"""

import pathlib
import sys

SECTOR = 256
MAX_LINE = 200          # the terminal input buffer is one page at $0200
SRCTRACK = 8            # after the kernel, with room for it to grow
SRCILEAVE = 1           # a sector is compiled far slower than the disk turns,
                        # so spacing them out would buy nothing


def pack(lines):
    """Lines into 256-byte sectors, zero padded, none of them split."""
    sectors, cur = [], bytearray()
    for line in lines:
        rec = line.encode("ascii") + b"\r"
        if len(cur) + len(rec) + 1 > SECTOR:        # +1 for the end marker
            sectors.append(bytes(cur).ljust(SECTOR, b"\x00"))
            cur = bytearray()
        cur += rec
    if cur:
        sectors.append(bytes(cur).ljust(SECTOR, b"\x00"))
    return sectors


def main(argv):
    if len(argv) != 4:
        print(__doc__)
        return 2
    src, binary, inc = (pathlib.Path(a) for a in argv[1:])

    lines = []
    for number, raw in enumerate(src.read_text().splitlines(), 1):
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("\\"):
            continue                                    # comment or blank
        if len(line) > MAX_LINE:
            raise SystemExit(f"{src}:{number}: line is {len(line)} chars, "
                             f"over the {MAX_LINE}-char input buffer")
        lines.append(stripped)                          # indentation is space

    # SRCEND -- the last track the source lands on -- is a fact only this
    # script knows, and INIT needs it on the machine to keep a formatted
    # boot disk bootable.  It used to be a kernel primitive, which cost
    # main-memory bytes PICSAVE could not spare; injected as the first
    # streamed line it compiles into the language card instead.  The value
    # is patched in after packing, at fixed width, so the count of sectors
    # it is derived from cannot be changed by the patch itself.
    lines.insert(0, "99 CONSTANT SRCEND")
    sectors = pack(lines)
    end = SRCTRACK + (len(sectors) - 1) // 16
    lines[0] = f"{end:2} CONSTANT SRCEND"
    sectors = pack(lines)
    binary.write_bytes(b"".join(sectors))
    inc.write_text(
        f"; Generated by tools/mkboot.py from {src}.  Do not edit.\n"
        f"SRCSECS   = {len(sectors)}\n"
        f"SRCTRACK  = {SRCTRACK}\n"
        f"SRCILEAVE = {SRCILEAVE}\n")
    print(f"wrote {binary}: {len(lines)} lines of Forth in "
          f"{len(sectors)} sectors, from track {SRCTRACK}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
