#!/usr/bin/env python3
"""Turn the Apple II character generator ROM into a ca65 font table.

The hi-res screen is 280 pixels wide and a screen byte holds 7 of them, so a
7-wide glyph occupies exactly one byte column: 40 columns of text, each
character eight single-byte writes down consecutive raster rows.  That is why
this font is 7 wide rather than 5 -- it makes drawing text almost free.

The ROM stores one glyph per 8 bytes, indexed by display code, with bit 7 as
the inverse flag.  Its bit order is the mirror of the hi-res screen's -- hi-res
puts the leftmost pixel in bit 0 -- so every byte is reversed on the way out.
ASCII $20-$5F (space through underscore: uppercase, digits, punctuation) is
all an Apple ][+ can display, and maps to ROM index `ascii & $3F`.

The generated file is a build product and is not committed -- the glyph
shapes are Apple's, and this keeps them out of the repository.

    python3 tools/mkfont.py roms/apple2p/341-0036.chr build/font.inc
"""

import pathlib
import sys

FIRST, LAST = 0x20, 0x5F


def rev7(byte):
    """Mirror the low 7 bits: character ROM order -> hi-res order."""
    out = 0
    for bit in range(7):
        if byte >> bit & 1:
            out |= 1 << (6 - bit)
    return out


def main(argv):
    if len(argv) != 3:
        print(__doc__)
        return 2
    rom = pathlib.Path(argv[1]).read_bytes()
    if len(rom) != 2048:
        raise SystemExit(f"expected a 2048-byte character ROM, got {len(rom)}")

    lines = [
        "; Generated by tools/mkfont.py from the Apple II character ROM.",
        "; 7x8 glyphs for ASCII $20-$5F, bit 0 leftmost, bit 7 cleared.",
        "FONT:",
    ]
    for code in range(FIRST, LAST + 1):
        rows = [rev7(rom[(code & 0x3F) * 8 + r]) for r in range(8)]
        art = "".join("#" if rows[1] >> b & 1 else "." for b in range(7))
        glyph = chr(code) if code != 0x20 else "SP"
        lines.append("        .byte   " + ",".join(f"${r:02X}" for r in rows)
                     + f"   ; {glyph:2} {art}")
    pathlib.Path(argv[2]).write_text("\n".join(lines) + "\n")
    print(f"wrote {argv[2]}: {LAST - FIRST + 1} glyphs, "
          f"{(LAST - FIRST + 1) * 8} bytes")

    # Render a sample so a wrong bit order is obvious immediately.
    sample = "HELLO 0123 A2FORTHOS"
    for row in range(8):
        out = ""
        for ch in sample:
            byte = rev7(rom[(ord(ch) & 0x3F) * 8 + row])
            out += "".join("#" if byte >> b & 1 else " " for b in range(7))
        print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
