#!/usr/bin/env python3
"""Turn src/icons.txt into a ca65 bitmap table.

Icons are 14 pixels wide because a screen byte holds 7: an icon on an even
byte column lands on exactly one auxiliary byte and one main byte per row, so
drawing one is two stores per row with no shifting.

Each row becomes two bytes, low 7 bits used, bit 0 leftmost -- the same order
the screen itself uses.

    python3 tools/mkicons.py src/icons.txt build/icons.inc
"""

import pathlib
import sys

WIDTH, HEIGHT = 14, 16


def pack(row: str) -> tuple:
    """One row of art -> (left byte, right byte), bit 0 leftmost."""
    row = row.ljust(WIDTH)[:WIDTH]
    left = right = 0
    for i, ch in enumerate(row):
        if ch != '#':
            continue
        if i < 7:
            left |= 1 << i
        else:
            right |= 1 << (i - 7)
    return left, right


def main(argv):
    if len(argv) != 3:
        print(__doc__)
        return 2

    icons, name, rows = [], None, []
    for number, raw in enumerate(pathlib.Path(argv[1]).read_text().splitlines(), 1):
        line = raw.rstrip("\n")
        if line.startswith(":"):
            if name:
                icons.append((name, rows))
            name, rows = line[1:].strip(), []
            continue
        if name is None:
            continue                    # preamble, before the first :NAME
        if not line.strip():
            continue                    # blank separator between icons
        if len(rows) < HEIGHT:
            rows.append(line)
    if name:
        icons.append((name, rows))

    out = [
        f"; Generated by tools/mkicons.py from {argv[1]}.  Do not edit.",
        f"; {WIDTH}x{HEIGHT} icons, two bytes per row, bit 0 leftmost.",
        "",
        f"ICONBYTES = {HEIGHT * 2}",
        "",
        "ICONBASE:",
    ]
    for index, (name, rows) in enumerate(icons):
        rows = (rows + [""] * HEIGHT)[:HEIGHT]
        out.append(f"; --- {name} (index {index}) ---")
        for row in rows:
            left, right = pack(row)
            art = "".join("#" if ch == "#" else "." for ch in row.ljust(WIDTH)[:WIDTH])
            out.append(f"        .byte   ${left:02X},${right:02X}   ; {art}")
    out.append("")
    for index, (name, _) in enumerate(icons):
        out.append(f"ICON_{name} = {index}")

    pathlib.Path(argv[2]).write_text("\n".join(out) + "\n")
    print(f"wrote {argv[2]}: {len(icons)} icons "
          f"({', '.join(n for n, _ in icons)})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
